name: Release to Maven Central

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "maven"
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set release version
        run: mvn --batch-mode versions:set -DnewVersion="${{ github.event.release.tag_name }}"

      - name: Run tests
        run: mvn --batch-mode test

      - name: Deploy to Maven Central (OSSRH)
        run: mvn --batch-mode clean deploy -P release -Dchangelist= -Drevision="${{ github.event.release.tag_name }}"
        env:
          # MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          # MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
