name: Release to Maven Central

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "maven"
          server-id: central
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Determine Maven Version Components
        id: version # to identify the output
        run: |
          COMMIT_SHA_LONG="${{ github.sha }}"
          COMMIT_SHA_SHORT="${COMMIT_SHA_LONG:0:7}"

          REVISION_VAR=""
          SHA1_VAR=""
          CHANGELIST_VAR=""

          if [[ "${{ github.ref_type }}" == "tag" ]]; then
              TAG_NAME="${{ github.ref_name }}"
              TAG_CLEAN=$(echo "$TAG_NAME" | sed 's/^v//')

              REVISION_VAR="$TAG_CLEAN"
              SHA1_VAR=""
              CHANGELIST_VAR=""
              echo "🏗️ Version de Release (Tag) détectée : $TAG_CLEAN"
          else
              LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0") 
              VERSION_BASE=$(echo "$LAST_TAG" | sed 's/^v//')
              IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_BASE"
              NEXT_PATCH=$((PATCH + 1))
              
              REVISION_VAR="$MAJOR.$MINOR.$NEXT_PATCH"
              SHA1_VAR="-$COMMIT_SHA_SHORT" 
              CHANGELIST_VAR="-SNAPSHOT"
              echo "🧪 Version Snapshot détectée (basée sur $LAST_TAG) : ${REVISION_VAR}${SHA1_VAR}${CHANGELIST_VAR}"
          fi

          echo "revision=$REVISION_VAR" >> "$GITHUB_OUTPUT"
          echo "sha1=$SHA1_VAR" >> "$GITHUB_OUTPUT"
          echo "changelist=$CHANGELIST_VAR" >> "$GITHUB_OUTPUT"
          echo "➡️ Variables de sortie définies : revision='$REVISION_VAR', sha1='$SHA1_VAR', changelist='$CHANGELIST_VAR'"

      - name: Run tests
        run: |
          mvn -B --file pom.xml clean test -P test \
            "-Drevision=${{ steps.version.outputs.revision }}" \
            "-Dsha1=${{ steps.version.outputs.sha1 }}" \
            "-Dchangelist=${{ steps.version.outputs.changelist }}"

      - name: Deploy to Maven Central
        run: |
          mvn --batch-mode clean deploy -P release \
          -Dgpg.keyname="${{ secrets.OSSRH_GPG_KEY_ID }}" \
          "-Drevision=${{ steps.version.outputs.revision }}" \
          "-Dsha1=${{ steps.version.outputs.sha1 }}" \
          "-Dchangelist=${{ steps.version.outputs.changelist }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CI_DEPLOY_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
